name = "sanram"
uuid = "a31bcd0b-b064-4847-8299-f34605c689d0"
repo = "https://github.com/sanram-org/Registry"

[packages]
21fe5c4b-a943-414d-bf3e-516f24900631 = { name = "Muscle", path = "M/Muscle" }
634dcf3f-6aa7-47ba-9e85-1fb329c9ebfe = { name = "Networks", path = "N/Networks" }
d83dbd90-3e00-4b33-84f1-398adcf3b35e = { name = "DelegatorTraits", path = "D/DelegatorTraits" }
